"""create habit, city and state tables

Revision ID: eb69a69b72ad
Revises: 
Create Date: 2025-09-20 12:48:27.069999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb69a69b72ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('transporte', 'energia', 'alimentacao', name='categoryenum'), nullable=False),
    sa.Column('frequency', sa.Enum('diario', 'semanal', 'mensal', name='frequencyenum'), nullable=False),
    sa.Column('quantity', sa.Enum('km', 'kwh_economizados', 'refeicoes', name='unitenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit')
    op.drop_table('city')
    op.drop_table('state')
    # ### end Alembic commands ###
